language: generic

go:
  - 1.12.x

os: linux
dist: bionic
  
services:
  - docker

# Delete git repo setup from travis
# and replace with git clone to master.
# reset hard to $TRAVIS_COMMIT
install:
  - . ./ci/git_setup.sh

before_script:
  - ./ci/download_cli.sh

script:
  - . ./ci/build.sh
  - . ./ci/list_artifacts.sh

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    branch: master
